source 'https://github.com/CocoaPods/Specs.git'

target 'HRSymbolFontKit', :exclusive => true do
  pod "HRSymbolFontKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HRSymbolFontKit", :path => "../"

  
end
